<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Venue;
class VenuesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $venues = array(
            array('id' => '1','title' => 'Emirates Palace','description' => 'One of the most iconic hotels in Abu Dhabi, Emirates Palace is a true symbol of luxury. It features lavish Arabian-style architecture, opulent interiors, and a private beach.','address' => '.','url' => 'https://www.mandarinoriental.com/en/abu-dhabi/emirates-palace','price' => '$$$$$','activity_type' => 'hotel','created_at' => '2023-08-03 18:22:08','updated_at' => '2023-08-03 18:25:41','destination_id' => '11'),
            array('id' => '2','title' => 'Shangri-La Qaryat Al Beri','description' => 'Offering a luxurious and tranquil retreat for guests, with its stunning Arabian-inspired architecture, private beach and exceptional dining options.','address' => '.','url' => 'https://www.shangri-la.com/en/abudhabi/shangrila/','price' => '$$$','activity_type' => 'hotel','created_at' => '2023-08-03 18:25:15','updated_at' => '2023-08-03 18:25:15','destination_id' => '11'),
            array('id' => '3','title' => 'Aloft','description' => 'Stylish and contemporary hotel, conveniently located in the centre of town and close to many popular tourist attractions. It offers all the modern comforts at a modest price.','address' => '.','url' => 'https://www.marriott.com/en-gb/hotels/travel/auhnl-aloft-abu-dhabi/','price' => '$$','activity_type' => 'hotel','created_at' => '2023-08-03 18:26:46','updated_at' => '2023-08-03 18:26:46','destination_id' => '11'),
            array('id' => '4','title' => 'Louvre','description' => 'Explore the Louvre, an art and civilization museum that houses a diverse collection of artworks from around the world. The museum\'s unique architecture and stunning exhibitions make it a must-visit.','address' => '.','url' => 'https://www.louvreabudhabi.ae/','price' => '.','activity_type' => 'activity','created_at' => '2023-08-03 18:28:51','updated_at' => '2023-08-03 18:28:51','destination_id' => '11'),
            array('id' => '5','title' => 'Qasr Al Watan, the Presidential Palace','description' => 'Visit Qasr Al Watan, the Presidential Palace, to explore the stunning architecture and learn about the UAE\'s governance and heritage. Take a guided tour to discover the palace\'s grand halls, exhibitions, and beautiful gardens.','address' => '.','url' => 'https://www.qasralwatan.ae/','price' => '.','activity_type' => 'activity','created_at' => '2023-08-03 18:30:14','updated_at' => '2023-08-03 18:30:14','destination_id' => '11'),
            array('id' => '6','title' => 'Desert Safari','description' => 'Experience the thrill of a desert safari. Take a thrilling dune bashing ride, try sandboarding, ride a camel and enjoy a traditional BBQ diner under the stars.','address' => '.','url' => 'https://www.abudhabi-desert-safari.com/','price' => '.','activity_type' => 'activity','created_at' => '2023-08-03 18:31:02','updated_at' => '2023-08-03 18:31:02','destination_id' => '11'),
            array('id' => '7','title' => 'BBQ Al Qasr','description' => 'Situated at the Emirates Palace, enjoy an evening of casual dining in a private sea front Gazebo, voted most romantic restaurant in Abu Dhabi.','address' => '.','url' => 'https://www.mandarinoriental.com/en/abu-dhabi/emirates-palace/dine/bbq-al-qasr','price' => '$$$','activity_type' => 'restaurant','created_at' => '2023-08-03 18:31:59','updated_at' => '2023-08-03 18:58:14','destination_id' => '11'),
            array('id' => '8','title' => 'Penelope\'s','description' => 'Situated in Yas Marina, this super cool Jazz bar and Brasserie, oozes class and takes diners back to the glamour of the jazz age French riviera. Enjoy a classic menu, bespoke crafted cocktails and stunning views of the Arabian gulf.','address' => '.','url' => 'https://www.penelopes.ae/','price' => '$$','activity_type' => 'restaurant','created_at' => '2023-08-03 18:33:07','updated_at' => '2023-08-03 18:59:00','destination_id' => '11'),
            array('id' => '9','title' => 'Beach House','description' => 'Beachfront restaurant, offering a relaxed and casual atmosphere by the sea, serving a menu of Mediterranean-inspired dishes.','address' => '.','url' => 'https://www.hyattrestaurants.com/en/dining/uae/abudhabi/-mediterranean-restaurant-in-saadiyat-island-beach-house','price' => '$$$','activity_type' => 'restaurant','created_at' => '2023-08-03 18:34:15','updated_at' => '2023-08-03 18:35:34','destination_id' => '11'),
            array('id' => '10','title' => 'Azura Panoramic Lounge','description' => 'Located at the St Regis Hotek, this rooftop bar offers stunning panoramic views of the city skyline and Arabian gulf. Enjoy a cocktail out on the terrace in this vibrant atmosphere.','address' => '.','url' => 'https://www.azuraabudhabi.com/','price' => '.','activity_type' => 'nightlife','created_at' => '2023-08-03 18:36:32','updated_at' => '2023-08-03 18:36:32','destination_id' => '11'),
            array('id' => '11','title' => 'Dhow Dinner Cruise','description' => 'Embark on a dinner cruise aboard a traditional dhow vessel. Soak up the stunning views of Abu Dhabi at night whilst enjoying a meal in this unique setting.','address' => '.','url' => 'https://www.abudhabidhowcruise.com/','price' => '.','activity_type' => 'nightlife','created_at' => '2023-08-03 18:37:18','updated_at' => '2023-08-03 18:37:18','destination_id' => '11'),
            array('id' => '12','title' => 'Taxi\'s','description' => 'Taxi\'s are a popular and convenient mode of transportation in Abu Dhabi. You can easily find taxis throughout the city, either by hailing them on the street or booking through ride-hailing apps like Uber or Careem.','address' => '.','url' => '.','price' => '.','activity_type' => 'get_around','created_at' => '2023-08-03 18:39:03','updated_at' => '2023-08-03 18:51:35','destination_id' => '11'),
            array('id' => '13','title' => 'Maisons Wat Kor','description' => 'Located in a traditional Khmer village, this luxury hotel offers well-appointed rooms with traditional and modern design. The hotel features a swinning pool, a spa and a restaurant serving Khmer and Western dishes.','address' => '.','url' => 'https://www.maisonswatkor.com/','price' => '$$$$','activity_type' => 'hotel','created_at' => '2023-08-03 18:40:50','updated_at' => '2023-08-03 18:40:50','destination_id' => '10'),
            array('id' => '14','title' => 'Bambu Hotel','description' => 'This boutique hotel offers luxurious rooms and suites with elegant decor in a tranquil setting. It features a beautiful swinning pool, a spa and a on-site restaurant.','address' => '.','url' => 'https://www.bambuhotel.com/','price' => '$$','activity_type' => 'hotel','created_at' => '2023-08-03 18:42:11','updated_at' => '2023-08-03 18:42:11','destination_id' => '10'),
            array('id' => '15','title' => 'Cambana La Riviere','description' => 'A stunning boutique hotel, situated along the Sangkae river, guests can enjoy beautiful views in serene surroundings for ultimate relaxation.','address' => '.','url' => 'https://www.cambanalariviere.com/','price' => '$$','activity_type' => 'hotel','created_at' => '2023-08-03 18:42:11','updated_at' => '2023-08-03 18:52:05','destination_id' => '10'),
            array('id' => '16','title' => 'Public Ferries','description' => 'Abu Dhabi\'s waterfront location allows for public ferry services. The ferry system connects various destinations, inclusing Yas Island and Saadiyat Island. It\'s a scenic and enjoyable way to travel, especially for tourists.','address' => '.','url' => '.','price' => '.','activity_type' => 'get_around','created_at' => '2023-08-03 18:55:43','updated_at' => '2023-08-03 18:55:43','destination_id' => '11'),
            array('id' => '17','title' => 'Buses','description' => 'Abu Dhabi has an extensive bus network, they cover various routes across the city and are an economical way to get around. You can check the bus schedules and routes on the DoT\'s official website or through their smartphone app, "Darbi".','address' => '.','url' => '.','price' => '.','activity_type' => 'get_around','created_at' => '2023-08-03 18:56:50','updated_at' => '2023-08-03 18:56:50','destination_id' => '11'),
            array('id' => '18','title' => 'Damrey Sor Pagoda','description' => 'The Pagoda is known for it\'s beautiful architecture and serene surroundings. Visitors can explore the interior and grounds and learn about Cambodian Buddhism.','address' => '2 Street, Battambang 02000, Cambodia','url' => NULL,'price' => NULL,'activity_type' => 'activity','created_at' => '2023-08-03 19:01:02','updated_at' => '2023-08-03 19:01:02','destination_id' => '10'),
            array('id' => '19','title' => 'Battambang Night Market','description' => 'Enjoy delicious street food as well as bartering with the market traders for souvenirs, handmade crafts, jewellery and clothes in this vibrant and bustling atmosphere.','address' => 'Road No 1, Krong Battambang, Cambodia','url' => NULL,'price' => NULL,'activity_type' => 'activity','created_at' => '2023-08-03 19:01:57','updated_at' => '2023-08-03 19:01:57','destination_id' => '10'),
            array('id' => '20','title' => 'Angkor Express Boat','description' => 'Ferry boat from Battambang to Siem Reap along the beautifully scenic Mekong river. Enjoy the serene surroundings and Cambodian culture at a slow pace.','address' => NULL,'url' => 'https://angkorfocus.com/','price' => NULL,'activity_type' => 'activity','created_at' => '2023-08-03 19:02:51','updated_at' => '2023-08-03 19:02:51','destination_id' => '10'),
            array('id' => '21','title' => 'La Villa Battambang','description' => 'Located in a beautifully restored colonial building, it offers an elegant and intimate dining experience.','address' => '#159d, Battambang 02353 Cambodia','url' => NULL,'price' => NULL,'activity_type' => 'restaurant','created_at' => '2023-08-03 19:03:46','updated_at' => '2023-08-03 19:03:46','destination_id' => '10'),
            array('id' => '22','title' => 'White Rose Restaurant','description' => 'This place is popular with locals as well as tourist\'s for it\'s authentic Khmer dishes and famous homemade ice cream.','address' => 'Road No 2, Krong Battambang, Cambodia','url' => NULL,'price' => NULL,'activity_type' => 'restaurant','created_at' => '2023-08-03 19:04:34','updated_at' => '2023-08-03 19:04:34','destination_id' => '10'),
            array('id' => '23','title' => 'coconu Lyly - Restaurant and cooking school','description' => 'A charming restaurant offering traditional Cambodian cuisine, they also run group cooking classes for a more immersive culinary experience.','address' => '111, Krong Battambang, Cambodia','url' => NULL,'price' => NULL,'activity_type' => 'restaurant','created_at' => '2023-08-03 19:05:38','updated_at' => '2023-08-03 19:05:38','destination_id' => '10'),
            array('id' => '24','title' => 'Miss Wong - Cocktail bar','description' => 'Boasting a stylish 1920\'s art deco interior, this super cool bar, serves the best cocktails in town.','address' => 'Street 2, Phasar Nat, Battambang 02000 Cambodia','url' => NULL,'price' => NULL,'activity_type' => 'nightlife','created_at' => '2023-08-03 19:06:23','updated_at' => '2023-08-03 19:06:23','destination_id' => '10'),
            array('id' => '25','title' => 'The Balcony','description' => 'Lively night spot in a great location along the river, serving food, cocktails, pool and karoake.','address' => 'House 465 Rd No 1, Krong Battambang, Cambodia','url' => NULL,'price' => NULL,'activity_type' => 'nightlife','created_at' => '2023-08-03 19:07:10','updated_at' => '2023-08-03 19:07:10','destination_id' => '10'),
            array('id' => '26','title' => 'Vintage Wine Bar','description' => 'Enjoy local as well international wines, paired with baguette toasts in this super relaxing setting.','address' => '84 Rd No 2.5, Krong Battambang, Cambodia','url' => NULL,'price' => NULL,'activity_type' => 'nightlife','created_at' => '2023-08-03 19:08:10','updated_at' => '2023-08-03 19:08:10','destination_id' => '10'),
            array('id' => '27','title' => 'Tuk Tuk','description' => 'These three-wheeled vehicles can be found throughout the city and are a convenient and affordable way to get around. Negotiate the fare with the driver before starting your journey.','address' => NULL,'url' => NULL,'price' => NULL,'activity_type' => 'get_around','created_at' => '2023-08-03 19:09:13','updated_at' => '2023-08-03 19:09:13','destination_id' => '10'),
            array('id' => '28','title' => 'Cycling','description' => 'Battambang is a bicycle-friendly city, and renting a bicycle is a great way to explore at your own pace. Many questhouses and hotels offer bicycle rentals, and you can also find rental shops around town.','address' => NULL,'url' => NULL,'price' => NULL,'activity_type' => 'get_around','created_at' => '2023-08-03 19:11:04','updated_at' => '2023-08-03 19:11:04','destination_id' => '10'),
            array('id' => '29','title' => 'Walking','description' => 'Battambang\'s city center is relatively compact and many attractions are within walking distance of each other. Walking is a pleasant way to explore the city, especially in the Old Town area.','address' => NULL,'url' => NULL,'price' => NULL,'activity_type' => 'get_around','created_at' => '2023-08-03 19:11:59','updated_at' => '2023-08-03 19:11:59','destination_id' => '10'),
            array('id' => '30','title' => 'Le Boutique Hotel & Spa','description' => 'Luxury hotel located in the heart of Bordeaux\'s historic center. It is housed in a 18th-century building and offers a blend of classic elegance and contemporary design.','address' => NULL,'url' => 'https://www.hotelbordeauxcentre.com/','price' => '$$$$','activity_type' => 'hotel','created_at' => '2023-08-03 19:13:07','updated_at' => '2023-08-03 19:13:07','destination_id' => '9'),
            array('id' => '31','title' => 'Les Sources De Caudale','description' => 'Situated in the vineyards of Château Smith Haut Lafitte, this five-star hotel offers an unique and tranquil setting. Guests can enjoy gourmet dining and wine tastings at the hotel\'s own vineyard.','address' => NULL,'url' => 'https://sources-caudalie.com/','price' => '$$$$','activity_type' => 'hotel','created_at' => '2023-08-03 19:14:24','updated_at' => '2023-08-03 19:14:24','destination_id' => '9'),
            array('id' => '32','title' => 'B&B - La Maison Galiene','description' => 'Perfectly located within walking distance of the city centre and a host of popular tourist attractions, this B&B offers a comfortable stay for a modest price','address' => NULL,'url' => 'https://www.lamaisongaliene.com/','price' => '$$','activity_type' => 'hotel','created_at' => '2023-08-03 19:15:28','updated_at' => '2023-08-03 19:15:28','destination_id' => '9'),
            array('id' => '33','title' => 'La Cité du Vin','description' => 'This unique wine museum offers an immersive experience into the world of wine. Learn about the history, production and different varieties of wine through interactive exhibits, workshops and tastings.','address' => NULL,'url' => 'https://www.laciteduvin.com/fr','price' => NULL,'activity_type' => 'activity','created_at' => '2023-08-03 19:16:28','updated_at' => '2023-08-03 19:16:28','destination_id' => '9'),
            array('id' => '34','title' => 'Chartrons District','description' => 'Famous for it\'s quirky antique shops and vintage boutiques, the Chartrons district is a great place to discover unique treasures.','address' => 'Rue Notre Dame','url' => NULL,'price' => NULL,'activity_type' => 'activity','created_at' => '2023-08-03 19:17:20','updated_at' => '2023-08-03 19:17:20','destination_id' => '9'),
            array('id' => '35','title' => 'Garonne River Cruise','description' => 'Taking a cruise along the Garonne River is a fantastic way to see Bordeaux from a different perspective and enjoy the beautiful scenery whilst enjoying a glass of wine.','address' => NULL,'url' => 'https://lesbateauxbordelais.com/','price' => NULL,'activity_type' => 'activity','created_at' => '2023-08-03 19:18:14','updated_at' => '2023-08-03 19:18:14','destination_id' => '9'),
            array('id' => '36','title' => 'Restaurant Le Gabriel','description' => 'Located in the historic Place de la Bourse, this Michelin-starred restaurant offers a sophisticated dining experience. The elegant decor and attentive service add to the overall experience.','address' => NULL,'url' => 'https://www.lareserve-paris.com/','price' => '$$$$$','activity_type' => 'restaurant','created_at' => '2023-08-03 19:19:17','updated_at' => '2023-08-03 19:19:17','destination_id' => '9'),
            array('id' => '37','title' => 'La Tupina','description' => 'Located in the charming Saint Pierre district, La Typina is a rustic and traditional restaurant known for its hearty and authentic regional cuisine. It\'s a favourite among locals and visitors alike.','address' => NULL,'url' => 'https://latupina.com/','price' => '$$$','activity_type' => 'restaurant','created_at' => '2023-08-03 19:20:24','updated_at' => '2023-08-03 19:20:24','destination_id' => '9'),
            array('id' => '38','title' => 'Le Balancier','description' => 'Quirky restaurant with swing seats, delicious menu and a great wine list. Perfectly located in the centre of Bordeaux.','address' => NULL,'url' => 'https://lebalancier-bordeaux.eatbu.com/','price' => '$','activity_type' => 'restaurant','created_at' => '2023-08-03 19:21:10','updated_at' => '2023-08-03 19:21:10','destination_id' => '9'),
            array('id' => '39','title' => 'Le Siman','description' => 'This rooftop bar boast\'s the best views of Bordeaux\'s historic skyline, enjoy a drink on the terrace and soak up the scenery.','address' => NULL,'url' => 'https://www.siman-bordeaux.com/','price' => NULL,'activity_type' => 'nightlife','created_at' => '2023-08-03 19:22:03','updated_at' => '2023-08-03 19:22:03','destination_id' => '9'),
            array('id' => '40','title' => 'Miroir d\'Eau (Water Mirror)','description' => 'This is a must-see when you visit Bordeaux, especially at night. The world\'s largest mirror-effect pool provides another dimension to the already impressive Place de la Bourse.','address' => 'Pl. de la Bourse, 33000 Bordeaux, France','url' => NULL,'price' => NULL,'activity_type' => 'nightlife','created_at' => '2023-08-03 19:24:20','updated_at' => '2023-08-03 19:24:20','destination_id' => '9'),
            array('id' => '41','title' => 'Madame Pang','description' => 'Cool, laid-back restaurant & bar serving innovative cocktails & Chinese-inspired dim sum.','address' => NULL,'url' => 'https://madamepang.com/','price' => NULL,'activity_type' => 'nightlife','created_at' => '2023-08-03 19:25:15','updated_at' => '2023-08-03 19:25:15','destination_id' => '9'),
            array('id' => '42','title' => 'Tram','description' => 'Bordeaux as an extensive tram network that covers most areas of the city. The trams are clean, modern and easy to use. Tickets can be purchased at the tram stations or through the TBM mobile app.','address' => NULL,'url' => NULL,'price' => NULL,'activity_type' => 'get_around','created_at' => '2023-08-03 19:26:29','updated_at' => '2023-08-03 19:26:29','destination_id' => '9'),
            array('id' => '43','title' => 'V3 Cubed','description' => 'Bordeaux has a bike-sharing system called V3. With numerous bike stations located throughout the city, you can easily rent a bike for short trips or leisurely rides along the riverfront.','address' => NULL,'url' => NULL,'price' => NULL,'activity_type' => 'get_around','created_at' => '2023-08-03 19:27:37','updated_at' => '2023-08-03 19:27:37','destination_id' => '9'),
            array('id' => '44','title' => 'Walking','description' => 'Bordeaux is a compact city with many attractions within walking distance of each other. Exploring the city on foot is a great way to soak in the atmosphere and discover hidden gems.','address' => NULL,'url' => NULL,'price' => NULL,'activity_type' => 'get_around','created_at' => '2023-08-03 19:28:25','updated_at' => '2023-08-03 19:28:25','destination_id' => '9'),
            array('id' => '45','title' => 'Museum Hotel','description' => 'Situated in the town of Uchisar, this boutique hotel is renowned for its stunning view of the Cappadocian landscape and its collection of ancient artifacts. Each room is uniquely designed and offers luxuirous amentities.','address' => NULL,'url' => 'https://www.museumhotel.com.tr/','price' => '$$$$','activity_type' => 'hotel','created_at' => '2023-08-03 19:29:48','updated_at' => '2023-08-03 19:32:56','destination_id' => '8'),
            array('id' => '46','title' => 'Argos in Cappadocia','description' => 'Located in Uchisar, this hotel is built into the ancient caves and offers beautifully furnished rooms with modern amentities.','address' => NULL,'url' => 'https://www.argosincappadocia.com/','price' => '$$$$','activity_type' => 'hotel','created_at' => '2023-08-03 19:30:48','updated_at' => '2023-08-03 19:30:48','destination_id' => '8'),
            array('id' => '47','title' => 'Grand Cave Suites','description' => 'Situated in Goreme, this budget hotel offers cave-style rooms with modern amentities. It features a rooftop terrace with panoramic views, a restaurant and free Wi-Fi','address' => NULL,'url' => 'https://www.argosincappadocia.com/','price' => '$','activity_type' => 'hotel','created_at' => '2023-08-03 19:32:09','updated_at' => '2023-08-03 19:32:29','destination_id' => '11'),
            array('id' => '48','title' => 'Hot air balloon ride','description' => 'Cappadocia is famous for its hot air balloon rides, offering breath-taking views of the fairy chimneys and the stunning landscape at sunrise. It\'s a must do experience for anyone visiting the region.','address' => NULL,'url' => 'https://www.hotairballooncappadocia.com/','price' => NULL,'activity_type' => 'activity','created_at' => '2023-08-03 19:34:32','updated_at' => '2023-08-03 19:34:32','destination_id' => '8'),
            array('id' => '49','title' => 'Underground cities','description' => 'Visit the ancient underground cities of Derinkuyu or Kaymakli to discover the fascinating underground tunnels, rooms and churches.','address' => NULL,'url' => 'https://cappadocia4u.com/cappadocia-underground-cities/','price' => NULL,'activity_type' => 'activity','created_at' => '2023-08-03 19:35:40','updated_at' => '2023-08-03 19:35:40','destination_id' => '8'),
            array('id' => '50','title' => 'Göreme open air museum','description' => 'Located in the town of Göreme, the UNESCO World Heritage Site showcases a collection of rock-cut churches, monasteries and dwellings that date back to the 10th to 12th centuries.','address' => '50180 Göreme/Nevsehir Merkez/Nevsehir, Türkiye','url' => NULL,'price' => NULL,'activity_type' => 'activity','created_at' => '2023-08-03 19:37:23','updated_at' => '2023-08-03 19:37:23','destination_id' => '8'),
            array('id' => '51','title' => 'Seten Restaurant','description' => 'Located in Urgup, Seten Anatolian Cuisine is known for its gourmet Turkish dishes prepared with a modern twist. The restaurant offers a cozy and elegant atmosphere.','address' => NULL,'url' => 'https://www.setenrestaurant.com/','price' => '$$$','activity_type' => 'restaurant','created_at' => '2023-08-03 19:38:24','updated_at' => '2023-08-03 19:38:24','destination_id' => '8'),
            array('id' => '52','title' => 'Ziggy\'s Café','description' => 'Situated in Goreme, Ziggy\'s Restaurant offers a mix of Turkish and international cuisines in a stylish setting. The menu features a variety of dishes prepared with locally sourced ingredients.','address' => NULL,'url' => 'http://www.ziggycafe.com/','price' => '$$','activity_type' => 'restaurant','created_at' => '2023-08-03 19:39:38','updated_at' => '2023-08-03 19:39:38','destination_id' => '8'),
            array('id' => '53','title' => 'Top Deck Cave Restaurant','description' => 'Located in Goreme, Topdeck Cave Restaurant offers an unique dining experience in a cave setting. Serving a variety of Turkish and international dishes, guests can enjoy their meal while taking in panoramic views of the surrounding landscape.','address' => 'Hafiz Abdullah Efendi Sokak No 15, Göreme, Turkiye','url' => NULL,'price' => NULL,'activity_type' => 'restaurant','created_at' => '2023-08-03 19:41:43','updated_at' => '2023-08-03 19:41:43','destination_id' => '8'),
            array('id' => '54','title' => 'Turkish Night Show','description' => 'Turkish night shows are entertaining cultural performances featuring traditional Turkish music, dance and folklore. These shows often include live music, belly dancing and traditional Turkish food.','address' => 'Uranos - Sakarya Restaurant, Akbel Mevkii, Ikinci tas köprü karsisi Gülsehir Yolu Avanos/ Nevsehir','url' => NULL,'price' => NULL,'activity_type' => 'nightlife','created_at' => '2023-08-03 19:44:15','updated_at' => '2023-08-03 19:44:15','destination_id' => '8'),
            array('id' => '55','title' => 'Kadika Roof Top Bar','description' => 'Take in Cappadocia\'s stunning night time views, whilst enjoying a perfectly crafted cocktail.','address' => 'Temenni, ESAT AGA SOK, 50400 Ürgüp/ Nevsehir, Türkiye','url' => NULL,'price' => NULL,'activity_type' => 'nightlife','created_at' => '2023-08-03 19:45:56','updated_at' => '2023-08-03 19:45:56','destination_id' => '8'),
            array('id' => '56','title' => 'Stargazing','description' => 'Cappadocia is known for its clear skies, making it a great place for stargazing. You can head to open fields or viewpoints away from city lights to enjoy the beauty of the night sky. Some hotels and tour companies also organize stargazing tours.','address' => NULL,'url' => NULL,'price' => NULL,'activity_type' => 'nightlife','created_at' => '2023-08-03 19:46:59','updated_at' => '2023-08-03 19:46:59','destination_id' => '8'),
            array('id' => '57','title' => 'Public Transport - Buses','description' => 'Buses, known as dolmus, connect the main towns and villages in the region. They run on fixed routes and can take you to all the popular destinations. Dolmus stops are usuaslly located near major hotels and tourist areas.','address' => NULL,'url' => NULL,'price' => NULL,'activity_type' => 'get_around','created_at' => '2023-08-03 19:48:19','updated_at' => '2023-08-03 19:48:19','destination_id' => '8'),
            array('id' => '58','title' => 'Cycling','description' => 'Cappadocia\'s unique landscape is perfect for cycling enthusiasts. You can rent a bicycle and explore the valleys, villages and fairy chimneys at your own pace.','address' => NULL,'url' => NULL,'price' => NULL,'activity_type' => 'get_around','created_at' => '2023-08-03 19:49:03','updated_at' => '2023-08-03 19:49:03','destination_id' => '8'),
            array('id' => '59','title' => 'Walking','description' => 'Cappadocia\'s towns and villages are relatively small and can be easily explored on foot. Walking allows you to soak in the charming atmosphere and discover hidden gems along the way.','address' => NULL,'url' => NULL,'price' => NULL,'activity_type' => 'get_around','created_at' => '2023-08-03 19:49:44','updated_at' => '2023-08-03 19:49:44','destination_id' => '8'),
            array('id' => '60','title' => 'Rachamankha','description' => 'This boutique hotel is located in the heart of the Old City. It\'s beautiful rooms, serene courtyard and attention to detail, provide guests with a tranquil and luxurious stay.','address' => NULL,'url' => 'https://www.rachamankha.com/','price' => '$$$','activity_type' => 'hotel','created_at' => '2023-08-03 19:50:50','updated_at' => '2023-08-03 19:50:50','destination_id' => '7'),
            array('id' => '61','title' => 'The Inside House','description' => 'This bourique hotel stands out with distinctive interior design inspired by traditional Thai houses. Each room is decorated with antique furniture and artifacts, creating an unique and nostalgic ambiance.','address' => NULL,'url' => 'https://www.the-insidehouse.com/','price' => '$$$','activity_type' => 'hotel','created_at' => '2023-08-03 19:51:52','updated_at' => '2023-08-03 19:51:52','destination_id' => '7'),
            array('id' => '62','title' => 'De Chai the Deco Hotel','description' => 'Located in the Nimman area, this budget hotel boasts\'s modern rooms, a roof top swimming pool and restaurant.','address' => NULL,'url' => 'https://deco-chiangmai.dechaihotel.com/','price' => '$','activity_type' => 'hotel','created_at' => '2023-08-03 19:52:37','updated_at' => '2023-08-03 19:52:37','destination_id' => '7'),
            array('id' => '63','title' => 'Wat Phra That Doi Suthep','description' => 'Situated on a mountain just outside the city, this iconic temple offers stunning views of Chiang Mai and houses a revered golden pagoda.','address' => NULL,'url' => 'https://www.tourismthailand.org/Attraction/wat-phra-that-doi-suthep/','price' => NULL,'activity_type' => 'activity','created_at' => '2023-08-03 19:53:28','updated_at' => '2023-08-03 19:53:50','destination_id' => '7'),
            array('id' => '64','title' => 'Night Bazaar','description' => 'Explore the vibrant Night Bazaar, where you can shop for handicrafts, clothing and souvenirs. Enjoy street food, live music and the bustling atmosphere.','address' => NULL,'url' => 'Changklan Rd. Chang Moi Sub-district, Mueang Chiang Mai','price' => NULL,'activity_type' => 'activity','created_at' => '2023-08-03 19:57:50','updated_at' => '2023-08-03 19:57:50','destination_id' => '7'),
            array('id' => '65','title' => 'Doi Inthanon National Park','description' => 'This national park is home to Thailand\'s highest peak, whether you\'re an avid hiker, nature enthusiast or simply looking for a peaceful escape from the city, Doi Inthanon offers a memorable experience with its natural beauty and serene surroundings.','address' => 'Mae Chaem District, Chiang Mai, Thailand','url' => NULL,'price' => NULL,'activity_type' => 'activity','created_at' => '2023-08-03 19:59:13','updated_at' => '2023-08-03 19:59:13','destination_id' => '8'),
            array('id' => '66','title' => 'The House by Ginger','description' => 'Offering a fine dining experience. The restaurant\'s elegant setting, attentive service and refined menu make it a top choice for a luxury meal.','address' => NULL,'url' => 'https://www.thehousebygingercm.com/','price' => '$$$','activity_type' => 'restaurant','created_at' => '2023-08-03 20:00:08','updated_at' => '2023-08-03 20:00:08','destination_id' => '7'),
            array('id' => '67','title' => 'The Riverside Restaurant','description' => 'Located along the Ping River and offering a beautiful view. The menu is a mix of Thai and international dishes, including fresh seafood.','address' => NULL,'url' => 'http://www.theriversidechiangmai.com/','price' => '$$','activity_type' => 'restaurant','created_at' => '2023-08-03 20:01:06','updated_at' => '2023-08-03 20:02:46','destination_id' => '7'),
            array('id' => '68','title' => 'Aroon Rai','description' => 'Located in the heart of the Old City, the restaurant is known for its authentic flavours and traditional dishes. Aroon Rai offers a cozy and casual atmosphere, popular with locals and tourists alike.','address' => '45 Kotchasarn Rd, Tambon Chang Moi, Mueang, Chiang Mai District, Chaing Mai 50100','url' => NULL,'price' => NULL,'activity_type' => 'restaurant','created_at' => '2023-08-03 20:02:26','updated_at' => '2023-08-03 20:02:26','destination_id' => '7'),
            array('id' => '69','title' => 'The Roof at Sala Lanna','description' => 'This rooftop bar offers panoramic views of the Ping River and the city. It\'s a great place to enjoy a drink while taking in the sunset or the city lights at night.','address' => NULL,'url' => 'https://www.salahospitality.com/lanna/dine/','price' => NULL,'activity_type' => 'nightlife','created_at' => '2023-08-03 20:03:39','updated_at' => '2023-08-03 20:03:39','destination_id' => '7'),
            array('id' => '70','title' => 'Night time River Cruise','description' => 'Embark in a relaxing river cruise along the Ping River, where you can ejoy the city\'s illuminated skyline and peaceful ambiance of the water.','address' => NULL,'url' => 'https://maepingrivercruise.com/','price' => NULL,'activity_type' => 'nightlife','created_at' => '2023-08-03 20:04:31','updated_at' => '2023-08-03 20:04:31','destination_id' => '7'),
            array('id' => '71','title' => 'Nimman Neighbourhood Bar Hop','description' => 'Explore the vibrant and iverse Nimman neighbourhood, where you\'ll find a variety of trendy bars, clubs and live music venues.','address' => 'Nimmana Haeminda Rd Lane 11, Tambon Su Thep, Mueang Chiang Mai District.','url' => NULL,'price' => NULL,'activity_type' => 'nightlife','created_at' => '2023-08-03 20:05:34','updated_at' => '2023-08-03 20:05:34','destination_id' => '7'),
            array('id' => '72','title' => 'Tuk Tuk','description' => 'Tuk tuks are a comman mode of transportation in Chiang Mai. These three-wheeled vehicles can be found throughout the city and are a fun and affordable way to get around. However, it\'s important to negotiate the fare before getting in.','address' => NULL,'url' => NULL,'price' => NULL,'activity_type' => 'get_around','created_at' => '2023-08-03 20:06:33','updated_at' => '2023-08-03 20:06:33','destination_id' => '7'),
            array('id' => '73','title' => 'Songthaews','description' => 'Songthaews are red, converted pickup trucks with covered seating in the back. They operate as shared taxis, following set routes. You can flag one down or find them at designated pickup points. They are a cost-effective way to travel short distances within the city.','address' => NULL,'url' => NULL,'price' => NULL,'activity_type' => 'get_around','created_at' => '2023-08-03 20:07:39','updated_at' => '2023-08-03 20:07:39','destination_id' => '7'),
            array('id' => '74','title' => 'Walking','description' => 'Ciang Mai\'s Old City is relatively compact and can easily be explored on foot. Walking allows you to soak in the atmosphere of the city, explore its temples and discover hidden gems along the way.','address' => NULL,'url' => NULL,'price' => NULL,'activity_type' => 'get_around','created_at' => '2023-08-03 20:09:11','updated_at' => '2023-08-03 20:09:11','destination_id' => '7'),
            array('id' => '75','title' => 'Naman Retreat','description' => 'Situated on the beautiful Non Nuoc Beach, Naman Retrat offers a luxurious and transquil retreat. The resort features elegant villas with private pools, a spa, wellness programs and a beachfront infinity pool.','address' => NULL,'url' => 'https://www.namanretreat.com/en','price' => '$$$$','activity_type' => 'hotel','created_at' => '2023-08-03 20:10:23','updated_at' => '2023-08-03 20:10:23','destination_id' => '6'),
            array('id' => '76','title' => 'Mercure Danang French Village Bana Hills','description' => 'Charming boutique hotel allows guests to immerse themselves in an unique and enchanting atmosphere, combining the beauty of the Ba Na Hills with a touch of French elegance.','address' => NULL,'url' => 'https://www.theedisonhotels.com/','price' => '$$$','activity_type' => 'hotel','created_at' => '2023-08-03 20:11:27','updated_at' => '2023-08-03 20:11:27','destination_id' => '6'),
            array('id' => '77','title' => 'Grand Sunrise','description' => 'Situatied in the An Thuong area a popular neighbourhood for tourists, this boutique hotel features a swimming pool, fitness centre, bar and restaurant.','address' => NULL,'url' => 'http://www.grandsunriseboutiquehotel.com/','price' => '$','activity_type' => 'hotel','created_at' => '2023-08-03 20:12:21','updated_at' => '2023-08-03 20:12:21','destination_id' => '6'),
            array('id' => '78','title' => 'Marble Mountains','description' => 'Explore the stunning Marble Mountains, a cluster of limestone hills with caves, pagodas and panoramic views. Climb to the top to enjoy the breath-taking vistas of the surrounding area.','address' => NULL,'url' => 'https://nguhanhson.org/','price' => NULL,'activity_type' => 'activity','created_at' => '2023-08-03 20:13:15','updated_at' => '2023-08-03 20:13:15','destination_id' => '6'),
            array('id' => '79','title' => 'Hoi An Ancient Town','description' => 'Take a short trip from Da Nang to Hoi An, a UNESCO World Hertage site. Wander through the narrow streets, admire the well-preserved architecture and visit historic sites like the Japanese Covered Bridge.','address' => NULL,'url' => 'https://whc.unesco.org/en/list/948/','price' => NULL,'activity_type' => 'activity','created_at' => '2023-08-03 20:14:26','updated_at' => '2023-08-03 20:14:26','destination_id' => '6'),
            array('id' => '80','title' => 'My Khe Beach','description' => 'Spend a day lounging on the golden sands of My Khe Beach, one of the most beautiful and pristine beaches in Vietnam.','address' => NULL,'url' => 'http://mykhebeach.org/','price' => NULL,'activity_type' => 'activity','created_at' => '2023-08-03 20:15:13','updated_at' => '2023-08-03 20:15:13','destination_id' => '6'),
            array('id' => '81','title' => 'La Maison 1888','description' => 'Located at the InterContinental Danang Sun Peninsula Resort, La Maison 1888 was the first restaurant to be awarded a Michelin star in Vietnam. Renowned for it\'s exceptional cuisine and high-quality fine dining experience.','address' => NULL,'url' => 'https://www.danang.intercontinental.com/dining/la-maison-1888/','price' => '$$$$$','activity_type' => 'restaurant','created_at' => '2023-08-03 20:16:50','updated_at' => '2023-08-03 20:16:50','destination_id' => '6'),
            array('id' => '82','title' => 'Madame Lân','description' => 'Located close to the Han River, Madame Lân is known for it\'s laid back atmosphere and delicious authentic Vietnamese menu. An essential pit stop for any visitor to Da Nang.','address' => NULL,'url' => 'https://www.madamelan.vn/','price' => '$$$','activity_type' => 'restaurant','created_at' => '2023-08-03 20:18:01','updated_at' => '2023-08-03 20:18:01','destination_id' => '6'),
            array('id' => '83','title' => 'Thai Gö','description' => 'Located in the heart of Da Nang, Thai Gö serves traditional Vietnamese cuisine with a modern twist. A cosy spot, popular with locals and tourists alike, the menu is extensive and very reasonably priced.','address' => NULL,'url' => 'http://thiagorestaurantdanang.com/','price' => '$','activity_type' => 'restaurant','created_at' => '2023-08-03 20:19:17','updated_at' => '2023-08-03 20:19:17','destination_id' => '6'),
            array('id' => '84','title' => 'Sky 36 Bar','description' => 'Located on the 36th floor of Novotel Danang Premier Han River, Sky36 is the highest rooftop bar in Da Nang. It offers stunning panoramic views of the city skyline, a stylish ambiance.','address' => '36 Bach Dang, Street, Hai Chau, Da Nang 5500000, Vietnam','url' => NULL,'price' => NULL,'activity_type' => 'nightlife','created_at' => '2023-08-03 20:20:40','updated_at' => '2023-08-03 20:20:40','destination_id' => '6'),
            array('id' => '85','title' => 'New Phuong Dong Nightclub','description' => 'Located in the heart of the City, night owls who want to extend the party into the early morning hours, can dance the night away in this state of the art night spot.','address' => '20 Dong Da, Thuan Phuoc, Hai Chau, Da Nang 5500000, Vietnam','url' => NULL,'price' => NULL,'activity_type' => 'nightlife','created_at' => '2023-08-03 20:21:41','updated_at' => '2023-08-03 20:21:41','destination_id' => '6'),
            array('id' => '86','title' => 'Da Nang Night Market','description' => 'Take a leasurely stroll through this vibrant and bustling market that comes alive at night. Sample the sites, sounds, smells and tastes of this wonderufl melting pot of crafts, culture and cuisine.','address' => '4 An Thuong 4, Da Nang, Vietnam','url' => NULL,'price' => NULL,'activity_type' => 'nightlife','created_at' => '2023-08-03 20:22:51','updated_at' => '2023-08-03 20:22:51','destination_id' => '6'),
            array('id' => '87','title' => 'Cyclos','description' => 'Cyclos are three-wheeled vehicles with a seat in the front for passengers. They are a traditional mode of transportatoin in Vietnam and offer an unique way to explore the city. Negotiate the fare before getting on a cyclo, as they usually do not have meters.','address' => NULL,'url' => NULL,'price' => NULL,'activity_type' => 'get_around','created_at' => '2023-08-03 20:24:01','updated_at' => '2023-08-03 20:24:01','destination_id' => '6'),
            array('id' => '88','title' => 'Grab/ride-hailing services','description' => 'Grab is a popular ride-hailing service, you can download the Grab app on your smartphone and easily book a ride to your desired destination.','address' => NULL,'url' => NULL,'price' => NULL,'activity_type' => 'get_around','created_at' => '2023-08-03 20:25:04','updated_at' => '2023-08-03 20:25:04','destination_id' => '6'),
            array('id' => '89','title' => 'Walking','description' => 'Da Nang is a relatively compact city and many attractions are within walking distance of each other, especially in the city centre. Walking can be a pleasant way to explore the local street, markets and riverfront areas.','address' => NULL,'url' => NULL,'price' => NULL,'activity_type' => 'get_around','created_at' => '2023-08-03 20:26:04','updated_at' => '2023-08-03 20:26:04','destination_id' => '6'),
            array('id' => '90','title' => 'QT Melbourne','description' => 'Trendy and stylish boutique hotel located in the heart of Melbourne\'s Central Business District. Known for its quirky and eclectic design, QT Melbourne offers an unique and vibrant atmosphere for guests.','address' => NULL,'url' => 'https://www.qthotels.com/melbourne','price' => '$$$','activity_type' => 'hotel','created_at' => '2023-08-03 20:28:35','updated_at' => '2023-08-03 20:28:35','destination_id' => '5'),
            array('id' => '91','title' => 'Hotel No.','description' => 'Accessed via a secret "speak easy" entrance and located on a car park rooff top, stay inside quirky 1970\'s style chrome air stream trailer which offer an unique setting and hotel experience.','address' => NULL,'url' => 'https://hotelno.melbourne/','price' => '$$','activity_type' => 'hotel','created_at' => '2023-08-03 20:29:31','updated_at' => '2023-08-03 20:29:47','destination_id' => '5'),
            array('id' => '92','title' => 'Jazz Corner Hotel','description' => 'Located within walking distance to the Cities key tourist attractions, this jazz themed hotel is a great base for exploring the Melbourne, is also has a jazz club in the basement.','address' => NULL,'url' => 'https://jazzcornerhotel.com/','price' => '$$','activity_type' => 'hotel','created_at' => '2023-08-03 20:31:02','updated_at' => '2023-08-03 20:31:02','destination_id' => '5'),
            array('id' => '93','title' => 'Street Art Laneways','description' => 'Melbourne is famous for its vibrant street art scene. Explore the laneways, such as Hosier Lane and AC/DC lane and admire the colourful and ever-changing murals.','address' => NULL,'url' => 'https://www.visitmelbourne.com/regions/melbourne/see-and-do/art-and-culture/public-art/vv-hosier-lane','price' => NULL,'activity_type' => 'activity','created_at' => '2023-08-03 20:31:54','updated_at' => '2023-08-03 20:31:54','destination_id' => '5'),
            array('id' => '94','title' => 'Melbourne Coffee Culture','description' => 'Melbourne is renowned for it\'s coffee culture. Explore the city\'s numerous cafes and sample some of the best coffee in town. Don\'t forget to try a classic Australian flat white!','address' => NULL,'url' => 'https://industrybeans.com/pages/fitzroy-cafe-and-roastery','price' => NULL,'activity_type' => 'activity','created_at' => '2023-08-03 20:33:53','updated_at' => '2023-08-03 20:33:53','destination_id' => '5'),
            array('id' => '95','title' => 'Queen Victoria Market','description' => 'Experience the bustling atmosphere of the Queen Victoria Market, one of Melbourne\'s iconic landsmarks. Browse through a wide range of fresh produce, clothing, souvenirs and tasty street food.','address' => NULL,'url' => 'https://qvm.com.au/','price' => NULL,'activity_type' => 'activity','created_at' => '2023-08-03 20:35:03','updated_at' => '2023-08-03 20:35:03','destination_id' => '5'),
            array('id' => '96','title' => 'Attica','description' => 'Attica is one of Melbourne\'s most acclaimed fine dining restaurants. Focusing on Australian ingredients and innovative techniques, this multi-course tasting menu showcases the best of Australian cuisine.','address' => NULL,'url' => 'https://www.attica.com.au/','price' => '$$$$$','activity_type' => 'restaurant','created_at' => '2023-08-03 20:36:51','updated_at' => '2023-08-03 20:36:51','destination_id' => '5'),
            array('id' => '97','title' => 'Cookie','description' => 'Known as one of Melbourne\'s best late night dining spots, Cookie, serves Australian and Thai small plates alongside a fantastic range of signature cocktails to create a night of good vibes and indulgence.','address' => NULL,'url' => 'https://www.cookiemelbourne.com.au/','price' => '$$','activity_type' => 'restaurant','created_at' => '2023-08-03 20:37:59','updated_at' => '2023-08-03 20:37:59','destination_id' => '5'),
            array('id' => '98','title' => 'Rice Paper Scissors','description' => 'A popular dining spot in Melbourne with 2x locations, Rice Paper Scissors is known for its vibrant and delicious Southeast Asian street food. A sharing style menu encourages a communal dining experience in a casuall setting.','address' => NULL,'url' => 'https://ricepaperscissors.com.au/','price' => '$$','activity_type' => 'restaurant','created_at' => '2023-08-03 20:48:24','updated_at' => '2023-08-03 20:48:24','destination_id' => '5'),
            array('id' => '99','title' => 'DaHa Bar','description' => 'Located on the 15th Floor and providing unparalleled views of Melbourne\'s city scape, this trendy balcony bar brings the party vibes with live DJ\'s set\'s providing the soundtrack to your weekend.','address' => NULL,'url' => 'https://www.dahaproject.com.au/','price' => NULL,'activity_type' => 'nightlife','created_at' => '2023-08-03 20:51:06','updated_at' => '2023-08-03 20:56:54','destination_id' => '5'),
            array('id' => '100','title' => 'Full Moon Fever','description' => 'Super hip rooftop bar, serving perfectly crafted cocktails under the sun.','address' => 'Upstairs 225 Johnston Street Abbotsford','url' => NULL,'price' => NULL,'activity_type' => 'nightlife','created_at' => '2023-08-04 07:53:12','updated_at' => '2023-08-04 07:53:12','destination_id' => '5'),
            array('id' => '101','title' => 'Yarra River Cruise','description' => 'Experience Melbournes\'cityspace from a different perspective by taking a night cruise along the Yarra River. Enjoy the city lights and iconic landmarks while cruising along the water.','address' => NULL,'url' => 'https://www.melbcruises.com.au/sightseeing-cruises/yarra-river-cruises/','price' => NULL,'activity_type' => 'nightlife','created_at' => '2023-08-04 07:54:09','updated_at' => '2023-08-04 07:54:09','destination_id' => '5'),
            array('id' => '102','title' => 'Trams','description' => 'Melbourne is famour for its iconic tram netwerk, which is the largest in the world. Trams are a convenient way to get around the city centre and inner suburbs. Like trains, you will need a myki card for tram travel.','address' => NULL,'url' => NULL,'price' => NULL,'activity_type' => 'get_around','created_at' => '2023-08-04 07:55:04','updated_at' => '2023-08-04 07:55:04','destination_id' => '5'),
            array('id' => '103','title' => 'Bike Share','description' => 'Melbourne offers a bike-sharing program called Melbourne Bike Share. You can rent bicycles from various docking stations across the city and explore at your own pace. Just register online or at a docking station to start using the bikes.','address' => NULL,'url' => NULL,'price' => NULL,'activity_type' => 'get_around','created_at' => '2023-08-04 07:55:50','updated_at' => '2023-08-04 07:55:50','destination_id' => '5'),
            array('id' => '104','title' => 'Walking','description' => 'Melbourne city centre is compact and pedestrian-friendly, making walking a great option for getting around. Many popular attractions, restaurants and shopping areas are within walking distance of each other.','address' => NULL,'url' => NULL,'price' => NULL,'activity_type' => 'get_around','created_at' => '2023-08-04 07:56:39','updated_at' => '2023-08-04 07:56:39','destination_id' => '5'),
            array('id' => '105','title' => 'Eastern & Oriental Hotel','description' => 'A colonial-style luxury hotel located in the heart of George Town. Indulge in spacious rooms, exquisite dining options and breath-taking views of the sea.','address' => NULL,'url' => 'https://www.eohotels.com/','price' => '$$$$','activity_type' => 'hotel','created_at' => '2023-08-04 07:57:32','updated_at' => '2023-08-04 07:58:24','destination_id' => '4'),
            array('id' => '106','title' => 'The Edison','description' => 'A luxury boutique hotel located in George Town, it offers a sophisticated and elegant ambiance with beautifully designed rooms and impeccable service.','address' => NULL,'url' => 'https://www.theedisonhotels.com/','price' => '$$$$','activity_type' => 'hotel','created_at' => '2023-08-04 07:58:15','updated_at' => '2023-08-04 07:58:36','destination_id' => '4'),
            array('id' => '107','title' => 'Hotel Sentral Georgetown','description' => 'A budget hotel offering cozy rooms and a convenient location in George Town. Ideal for travelers looking for a comfortable stay at an affordable price.','address' => NULL,'url' => 'https://hotel-sentral-georgetown.h-rez.com/','price' => '$','activity_type' => 'hotel','created_at' => '2023-08-04 07:59:24','updated_at' => '2023-08-04 07:59:24','destination_id' => '4'),
            array('id' => '108','title' => 'George Town - Street Art','description' => 'George Town is famous for its street art, the numerous murtals and sculptures scattered throughout the UNESCO-lested historic district depict life & culture in Penang. Take a leisurely stroll to discover these vibrant artworks.','address' => '316, Beach st, 10300 George Town, Penang','url' => NULL,'price' => NULL,'activity_type' => 'activity','created_at' => '2023-08-04 08:00:38','updated_at' => '2023-08-04 08:00:38','destination_id' => '4'),
            array('id' => '109','title' => 'Kek Lok Si Temple','description' => 'One of the largest buddhist temples in Southeast Asia, known for its stunning architecture, intricate carvings and beautiful gardens.','address' => NULL,'url' => 'http://kekloksitemple.com/','price' => NULL,'activity_type' => 'activity','created_at' => '2023-08-04 08:42:01','updated_at' => '2023-08-04 08:42:01','destination_id' => '4'),
            array('id' => '110','title' => 'Penang Hill','description' => 'A hill station with a funicalur railway that offers panoramic views of the island. It\'s a popular spot of hiking, nature walks and enjoying cool mountain air.','address' => NULL,'url' => 'https://www.penanghill.gov.my/index.php/en/','price' => NULL,'activity_type' => 'activity','created_at' => '2023-08-04 08:42:45','updated_at' => '2023-08-04 08:42:45','destination_id' => '4'),
            array('id' => '111','title' => 'Kebaya Dining Room','description' => 'Located in the beautiful Seven Terraces boutique hotel, Kebaya Dining room offers a fusion of Malaysian and Western flavours in an elegant setting. Indulge in their meticulously crafted dishes that highlight local ingredients.','address' => NULL,'url' => 'https://kebaya.com.my/','price' => '$$$','activity_type' => 'restaurant','created_at' => '2023-08-04 08:43:49','updated_at' => '2023-08-04 08:43:49','destination_id' => '4'),
            array('id' => '112','title' => 'Indigo Restaurant at Indigo Mansion','description' => 'The Indigo Restaurant offers a luxurious dining experience. Enjoy a fusion of Western and Asian flavours in a beautifully restored mansion. The menu features exquisite dishes made from fresh, locally sourced ingredients.','address' => NULL,'url' => 'https://www.cheongfatttzemansion.com/restaurants','price' => '$$$','activity_type' => 'restaurant','created_at' => '2023-08-04 08:45:00','updated_at' => '2023-08-04 08:45:00','destination_id' => '4'),
            array('id' => '113','title' => 'Red Garden Food Paradise','description' => 'Located in the heart of Georgetown, Red Garden Food Paradise is a popular openair food court that offers a wide variety of Penang street food. You can find dishes like Char Kway Teow, Assam Laksa, Hokkien Mee and more.','address' => NULL,'url' => 'http://www.redgarden-food.com/','price' => NULL,'activity_type' => 'restaurant','created_at' => '2023-08-04 08:46:15','updated_at' => '2023-08-04 08:46:15','destination_id' => '4'),
            array('id' => '114','title' => '360 Revolving Rooftop Bar','description' => 'Situated on the 24th floor of Bayview Hotel Georgetown, this rooftop bar offers stunning panoramic views of the city skyline. Enjoy a wide selection of cocktails while taking in the breath-taking visitas.','address' => NULL,'url' => 'https://www.360rooftop.com.my/#','price' => NULL,'activity_type' => 'nightlife','created_at' => '2023-08-04 08:47:30','updated_at' => '2023-08-04 08:47:30','destination_id' => '4'),
            array('id' => '115','title' => 'Manchu Bar','description' => 'Manchu Bar offers an unique ambiance with its Chinese-inspired decor and vibrant atmosphere. It\'s a great place to enjoy a night out with friends or to experience Penang\'s nightlife scene.','address' => '38 & 40, Jalan Pintal Tali, George Town, Penang','url' => NULL,'price' => NULL,'activity_type' => 'nightlife','created_at' => '2023-08-04 08:48:57','updated_at' => '2023-08-04 08:48:57','destination_id' => '4'),
            array('id' => '116','title' => 'Good Friends Club','description' => 'Drink\'s connoisseurs frequent this bar for some of the most innovative cocktails on the island.','address' => '39 Jalan Gurdwara (Hin Bus Art Depot), George Town','url' => NULL,'price' => NULL,'activity_type' => 'nightlife','created_at' => '2023-08-04 08:49:49','updated_at' => '2023-08-04 08:49:49','destination_id' => '4'),
            array('id' => '117','title' => 'The Penang Ferry','description' => 'The Penang Ferry service operates between George Town on Penang Island and Butterworth on the mainland. It is a scenic and inexpensive way to travel between the two locations.','address' => NULL,'url' => NULL,'price' => NULL,'activity_type' => 'get_around','created_at' => '2023-08-04 08:50:29','updated_at' => '2023-08-04 08:50:29','destination_id' => '4'),
            array('id' => '118','title' => 'Grab/ride-hailing services','description' => 'Grab is a popular-hailing service in Penang, similar to Uber of Lyft. You can use the Grab app to book a car or taxi to take you to your desired destination. It\'s a convenient option if you prefer private transportation.','address' => NULL,'url' => NULL,'price' => NULL,'activity_type' => 'get_around','created_at' => '2023-08-04 08:52:54','updated_at' => '2023-08-04 08:52:54','destination_id' => '4'),
            array('id' => '119','title' => 'Trishaw','description' => 'Trishaws. or cycle rickshaws, are traditional modes of transportation in Penang. They are primarily found in George Town and can be a fun and unique way to explore the city. Negotiate the fare with the trishaw driver before starting your ride.','address' => NULL,'url' => NULL,'price' => NULL,'activity_type' => 'get_around','created_at' => '2023-08-04 08:53:57','updated_at' => '2023-08-04 08:53:57','destination_id' => '4'),
            array('id' => '120','title' => 'The Barracks Hotel','description' => 'Located on Sentosa Island, this luxury hotel is in a beautifully restored colonial building. It offers a tranquil and exclusive setting, away from the hustle and bustle of the city whilst still being easily accessible to the mainland.','address' => NULL,'url' => 'https://www.thebarrackshotel.com.sg/','price' => '$$$$','activity_type' => 'hotel','created_at' => '2023-08-04 08:58:03','updated_at' => '2023-08-04 08:58:03','destination_id' => '3'),
            array('id' => '121','title' => 'Hotel Mono','description' => 'Located in the heart of Chinatown, this hotel has an unique black-and-white color scheme throughout with clean lines and minimalist furnishings, creating a sleek and contemporary atmosphere.','address' => NULL,'url' => 'https://www.hotelmono.com/','price' => '$$','activity_type' => 'hotel','created_at' => '2023-08-04 08:59:03','updated_at' => '2023-08-04 08:59:03','destination_id' => '3'),
            array('id' => '122','title' => '1929','description' => 'Stylish and contemporary hotel located in 5 converted shop houses from 1929. This boutique hotel is conveniently located ni China town, close to the business district. It offers all the modren comforts at a modest price','address' => NULL,'url' => 'https://www.1929hotel.com/','price' => '$$','activity_type' => 'hotel','created_at' => '2023-08-04 09:00:25','updated_at' => '2023-08-04 09:00:25','destination_id' => '3'),
            array('id' => '123','title' => 'Gardens by the bay','description' => 'This nature park spans 101 hectares and is best known for its iconic Supertrees, which are vertical gardens ranging from 25 to 50 meters in height. A must visit destination for nature lovers seeking an unique experience.','address' => NULL,'url' => 'https://www.gardensbythebay.com.sg/','price' => NULL,'activity_type' => 'activity','created_at' => '2023-08-04 09:01:20','updated_at' => '2023-08-04 09:01:20','destination_id' => '3'),
            array('id' => '124','title' => 'Palawan Beach','description' => 'Located on Sentaosa Island the beach has white sandy shores, clear blue waters and lush greenery. Spend a day in the sun and recharge those batteries,
          ready for Singapore’s night time festivities.','address' => NULL,'url' => 'https://www.sentosa.com.sg/en/things-to-do/attractions/palawan-beach/','price' => NULL,'activity_type' => 'activity','created_at' => '2023-08-04 10:10:54','updated_at' => '2023-08-04 10:10:54','destination_id' => '3'),
            array('id' => '125','title' => 'Southern Ridges','description' => 'This scenic walking trail connects several parks and nature reserves in the Southern
          part of the city. Enjoy the lush landscapes and breath-taking views of the city along
          the 10Km trail.','address' => NULL,'url' => 'https://www.nparks.gov.sg/gardens-parks-and-nature/parks-and-nature- reserves/the-southern-ridges','price' => NULL,'activity_type' => 'activity','created_at' => '2023-08-04 10:11:19','updated_at' => '2023-08-04 10:11:19','destination_id' => '3'),
            array('id' => '126','title' => 'NOX dine in the dark','description' => 'Dine in the Dark aims to create awareness and empathy for the visually impaired
          community while providing a unique and immersive dining experience. It is a great
          opportunity to challenge your senses as well as your taste buds.','address' => NULL,'url' => 'https://www.noxdineinthedark.com','price' => '$$$$','activity_type' => 'restaurant','created_at' => '2023-08-04 10:11:47','updated_at' => '2023-08-04 10:11:47','destination_id' => '3'),
            array('id' => '127','title' => 'The Coconut Club','description' => 'Informal restaurant celebrating all things coconut. Enjoy the atmosphere and culinary delights of authentic Singaporean flavour’s, in particular the signature Nasi Lemak.','address' => NULL,'url' => 'https://www.thecoconutclub.sg','price' => '$','activity_type' => 'restaurant','created_at' => '2023-08-04 10:12:15','updated_at' => '2023-08-04 10:12:15','destination_id' => '3'),
            array('id' => '128','title' => 'Amoy Street Food Centre','description' => 'A popular hawker center located in the heart of Singapore&#39;s Central Business
          District. Enjoy the bustling atmosphere and a wide variety of local Singaporean and
          Asian dishes at affordable prices.','address' => '7 Maxwell Rd, Singapore 069111','url' => NULL,'price' => '$','activity_type' => 'restaurant','created_at' => '2023-08-04 10:12:55','updated_at' => '2023-08-04 10:12:55','destination_id' => '3'),
            array('id' => '129','title' => 'Atlas Bar','description' => 'Located on the ground floor of the iconic park view square building, relax in the bar’s
          truly grand art deco back drop whilst enjoying one of their perfectly crafted cocktails.','address' => NULL,'url' => 'Located on the ground floor of the iconic park view square building, relax in the bar’s truly grand art deco back drop whilst enjoying one of their perfectly crafted cocktails.','price' => NULL,'activity_type' => 'nightlife','created_at' => '2023-08-04 10:13:14','updated_at' => '2023-08-04 10:13:14','destination_id' => '3'),
            array('id' => '130','title' => 'Cable Car Sky Dining','description' => 'Enjoy a meal high above the city with this cable cabin dining experience. Take in the
          stunning views of Singapore at night from this unique setting.','address' => NULL,'url' => 'https://www.mountfaberleisure.com/restaurant/cable-car-sky-dining/','price' => NULL,'activity_type' => 'nightlife','created_at' => '2023-08-04 10:13:45','updated_at' => '2023-08-04 10:13:45','destination_id' => '3'),
            array('id' => '131','title' => 'Zouk Night Club','description' => 'Located on the Singapore river, dance into the early hours of the morning in one of
          Singapore’s most revered night spots.','address' => NULL,'url' => 'https://zoukclub.com','price' => NULL,'activity_type' => 'nightlife','created_at' => '2023-08-04 10:14:03','updated_at' => '2023-08-04 10:14:03','destination_id' => '3'),
            array('id' => '132','title' => 'MRT','description' => 'Singapore’s MRT metro system is a great way to travel the city with a MRT never too
          far away from the Cities main tourist attractions it is a convenient and efficient way to get around.','address' => NULL,'url' => NULL,'price' => NULL,'activity_type' => 'get_around','created_at' => '2023-08-04 10:14:22','updated_at' => '2023-08-04 10:14:22','destination_id' => '3'),
            array('id' => '133','title' => 'Taxi','description' => 'Taxi’s are a popular and convenient mode of transportation in Singapore. You can
          easily find taxis throughout the city, either by hailing them on the street or booking
          through ride-hailing apps like Grab and Ryde.','address' => NULL,'url' => NULL,'price' => NULL,'activity_type' => 'get_around','created_at' => '2023-08-04 10:14:35','updated_at' => '2023-08-04 10:14:35','destination_id' => '3'),
            array('id' => '134','title' => 'Bicycle','description' => 'Singapore offers a well connected network of cycling paths, travellers can rent
          bicycles from a number of operators and experience the City from a different
          perspective.','address' => NULL,'url' => NULL,'price' => NULL,'activity_type' => 'get_around','created_at' => '2023-08-04 10:14:48','updated_at' => '2023-08-04 10:14:48','destination_id' => '3')
          );
          
           

        // Insert the data into the 'venues' table
        foreach ($venues as $venueData) {
            Venue::create($venueData);
        }
    }
}
